[deployment]
hostname = "publisher.wso2.com"
local_member_ip = "127.0.0.1"
server_role = "api-publisher"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
hostname = "apim.mysql"
name = "apimgtdb"
port = "3306"
username = "apimuser"
password = "apimuser"

[database.shared_db]
type = "mysql"
hostname = "apim.mysql"
name = "apimgtdb"
port = "3306"
username = "shareduser"
password = "shareduser"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"


[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"


[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url= true
service_url= "https://gw.mgt.wso2.com:443/services/"
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"


[apim.analytics]
store_api_url = "https://analytics.wso2.com:7444"
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"

[[apim.analytics.analytics_node]]
analytics_url="tcp://analytic1.local:7612"
analytics_auth_url="ssl://analytic1.local:7712"

[[apim.analytics.analytics_node]]
analytics_url="tcp://analytic2.local:7612"
analytics_auth_url="ssl://analytic2.local:7712"

[apim.key_manager]
service_url = "https://km.wso2.com:443/services/"
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"


# Traffic Manager configurations
[apim.throttling]
service_url = "https://tm.wso2.com:443/services/"
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"

enable_data_publishing = true
enable_policy_deployer = true
enable_block_condition = false
enable_decision_connection = false

[[apim.throttling.nodes.group0]]
traffic_manager_url="tcp://tm1.local:9611"
traffic_manager_auth_url="ssl://tm1.local:9711"

[[apim.throttling.nodes.group1]]
traffic_manager_url="tcp://tm2.local:9611"
traffic_manager_auth_url="ssl://tm2.local:9711"

[apim.cache.scope]
enabled = true

[apim.cache.publisher_role]
enabled = true

[apim.store]
url = "https://store.wso2.com:443/store"

[apim.workflow]
enabled = false
service_url = "https://localhost:9445/bpmn"
username = "$conf{super_admin.username}"
password = "$conf{super_admin.password}"
callback_endpoint = "https://localhost:${mgt.transport.https.port}/api/am/publisher/v0.14/workflows/update-workflow-status"
token_endpoint = "https://localhost:${https.nio.port}/token"
client_registration_endpoint = "https://localhost:${mgt.transport.https.port}/client-registration/v0.14/register"
client_registration_username = "$conf{super_admin.username}"
client_registration_password = "$conf{super_admin.password}"
