[deployment]
hostname = "localhost"
local_member_ip = "127.0.0.1"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "h2"
url = "jdbc:h2:repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[apim.gateway.environment]
dev.name= "Production and Sandbox"
dev.type= "hybrid"
dev.display_in_api_console= true
dev.description= "This is a hybrid gateway that handles both production and sandbox token traffic."
dev.isDefault= true
dev.management_endpoint= "https://localhost:${mgt.transport.https.port}${carbon.context}services/"
dev.username= "${admin.username}"
dev.password= "${admin.password}"
dev.ws_endpoint= "ws://${carbon.local.ip}:9099"
dev.http_endpoint = "http://localhost:8280/"
dev.https_endpoint = "https://localhost:8243/"

[apim.cache]
#token
#resource
#km_token
#recent_api
#scope
#publisher_role
#jwt_claim

[apim.analytics]
#receiver_urls = "tcp://localhost:7611"
receiver_failover_url.group0.node0="tcp://localhost:7612"
receiver_failover_url.group0.node1="tcp://localhost:7612"
receiver_failover_url.group1.node0="tcp://localhost:7612"
receiver_failover_url.group1.node1="tcp://localhost:7612"
receiver_failover_auth_url.group0.node0="ssl://localhost:7712"
receiver_failover_auth_url.group0.node1="ssl://localhost:7712"
receiver_failover_auth_url.group1.node0="ssl://localhost:7712"
receiver_failover_auth_url.group1.node1="ssl://localhost:7712"
#receiver_username
#receiver_password
rest_api_url = "https://localhost:7444"

[apim.key_manager]
url = "https://localhost:9443/services/"

[apim.jwt]
generator_type = "default"
header = "X-JWT-Assertion"
dialect = "http://wso2.org/claims"
algo = "SHA256withRSA"
claims = "default"

[apim.oauth_config]
outflow_auth_header = "remove"
#outflow_auth_header = "keep" or "remove"
auth_header = "Authorization"
token_endpoint = "https://localhost:8243/token"
revoke_endpoint = "https://localhost:8243/revoke"
encrypt_persisted_token = "default"
token_hash_mode = "default"

[apim.store]
url = "https://localhost:9443/store"
display_url = "https://localhost:9443/store"
app_share_impl = "default"
service_url = "https://localhost:9443/services"
version_display_level = "all"
lifecycle_display_level = "all"
enable_comments = "true"
enable_ratings = "true"
enable_forum = "true"

[apim.publisher]
#display_url
#URL
#enable_access_control

[apim.cors]
allow_origins = "*"
allow_methods = "GET,PUT,POST,DELETE,PATCH,OPTIONS"
allow_headers = "authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction"
allow_credentials = "false"

[apim.throttling]
#receiver_url="tcp://localhost:9611"
receiver_failover_url.group0.node0="tcp://localhost:9611"
receiver_failover_url.group0.node1="tcp://localhost:9611"
receiver_failover_url.group1.node0="tcp://localhost:9611"
receiver_failover_url.group1.node1="tcp://localhost:9611"
receiver_failover_auth_url.group0.node0="ssl://localhost:9711"
receiver_failover_auth_url.group0.node1="ssl://localhost:9711"
receiver_failover_auth_url.group1.node0="ssl://localhost:9711"
receiver_failover_auth_url.group1.node1="ssl://localhost:9711"
publisher.enable="true"
jms.factory.type="andes"
jms.username = "admin"
jms.password = "admin"
jms.connection.node0 = "tcp://localhost:5672"
jms.connection.node1 = "tcp://localhost:5672"
#jms.topic_connection_factory= "amqp://${admin.username}:${admin.password}@clientid/carbon?brokerlist='tcp://${carbon.local.ip}:${jms.port}'"