[deployment]
hostname = "localhost"
local_member_ip = "127.0.0.1"
offset=0

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "h2"
url = "jdbc:h2:repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
isDefault= true
management_endpoint= "https://localhost:9443/services/"
username= "$ref{super_admin.username}"
password= "${admin.password}"
ws_endpoint= "ws://localhost:9099"
http_endpoint = "http://localhost:8280/"
https_endpoint = "https://localhost:8243/"

[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
isDefault= true
service_url= "https://localhost:9443/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint= "ws://localhost:9099"
http_endpoint = "http://localhost:8280/"
https_endpoint = "https://localhost:8243/"

[apim.cache]
[apim.cache.gateway_token]
enabled = true

[apim.cache.resource]
enabled = true

[apim.cache.km_token]
enabled = false

[apim.cache.recent_api]
enabled = false

[apim.cache.recent_api]
enabled = false

[apim.cache.scope]
enabled = true

[apim.cache.publisher_role]
enabled = true

[apim.cache.jwt_claim]
enabled = true

[apim.analytics]
store_api_url = "https://localhost:7444" #change the name
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"

[[apim.analytics.analytics_node]]
analytics_url="tcp://localhost:7612"
analytics_auth_url="ssl://localhost:7712"

[[apim.analytics.analytics_node]]
analytics_url="tcp://localhost:7612"
analytics_auth_url="ssl://localhost:7712"


[apim.key_manager]
service_url = "https://localhost:9443/services/"
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"
pool.init_idle_capacity=50
max_idle=100
custom_key_validation_handler="org.wso2.carbon.apimgt.keymgt.handlers.DefaultKeyValidationHandler"

[apim.jwt]
generator_type = "default" # default,url_safe or custom
#generator_type = "custom"
#generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
header = "X-JWT-Assertion"
dialect = "http://wso2.org/claims"
algo = "SHA256withRSA"
claims = "default" #or "custom",
claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"

[apim.oauth_config]
remove_outbound_auth_header = true
auth_header = "Authorization"
revoke_endpoint = "https://localhost:8243/revoke"
enable_token_encryption = false
enable_token_hashing = false

[apim.store]
url = "https://localhost:9443/store"
application_sharing_type = "default" #changed to type, saml, default, custom or rest # need to check the words # validate
application_sharing_impl = "org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl"
display_multiple_versions = false
display_deprecated_apis = false
enable_comments = true
enable_ratings = true
enable_forum = true

[apim.cors]
enable = true
allow_origins = "*"
allow_methods = "GET,PUT,POST,DELETE,PATCH,OPTIONS"
allow_headers = "authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction"
allow_credentials = "false"

[apim.throttling.node]
[[group0]]
[[node0]]
traffic_manager_url="tcp://localhost:7612"
traffic_manager_auth_url="ssl://localhost:7712"
[[node1]]
traffic_manager_url="tcp://localhost:7612"
traffic_manager_auth_url="ssl://localhost:7712"

[[group1]]
[[node0]]
traffic_manager_url="tcp://localhost:7612"
traffic_manager_auth_url="ssl://localhost:7712"
[[node1]]
traffic_manager_url="tcp://localhost:7612"
traffic_manager_auth_url="ssl://localhost:7712"

#receiver_url="tcp://localhost:9611"
enable_data_publishing="true"
throttle_decision_endpoints = ["tcp://localhost:5672","tcp://localhost:5672"]
