[deployment]
hostname = "localhost"
local_member_ip = "127.0.0.1"
offset=0

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "h2"
url = "jdbc:h2:repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE"
username = "wso2carbon"
password = "wso2carbon"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[[apim.gateway.environment]]
name = "Production and Sandbox"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "https://localhost:9443/services/"
username = "$conf{super_admin.username}"
password = "$conf{super_admin.password}"
ws_endpoint = "ws://localhost:9099"
http_endpoint = "http://localhost:8280/"
https_endpoint = "https://localhost:8243/"

[apim.cache.gateway_token]
enabled = true
expiry_time = 15

[apim.cache.resource]
enabled = true

[apim.cache.km_token]
enabled = false
expiry_time = 15

[apim.cache.recent_api]
enabled = false

[apim.cache.scope]
enabled = true

[apim.cache.publisher_role]
enabled = true

[apim.cache.jwt_claim]
enabled = true
expiry_time = 900

[apim.cache.tag]
expiry_time = 120000

[apim.analytics]
store_api_url = "https://localhost:7444"
username = "$conf{super_admin.username}"
password = "$conf{super_admin.password}"
event_publisher_type = "default"
#event_publisher_type = "custom"
#event_publisher_impl = "org.wso2.carbon.apimgt.usage.publisher.APIMgtUsageDataBridgeDataPublisher"

[[apim.analytics.analytics_node]]
analytics_url ="tcp://localhost:7612"
analytics_auth_url ="ssl://localhost:7712"

[[apim.analytics.analytics_node]]
analytics_url = "tcp://localhost:7612"
analytics_auth_url = "ssl://localhost:7712"


[apim.key_manager]
service_url = "https://localhost:9443/services/"
username = "$conf{super_admin.username}"
password = "$conf{super_admin.password}"
pool.init_idle_capacity = 50
pool.max_idle = 100
key_validation_handler_type = "default"
#key_validation_handler_type = "custom"
#key_validation_handler_impl = "org.wso2.carbon.apimgt.keymgt.handlers.DefaultKeyValidationHandler"

[apim.jwt]
generator_type = "default" # default,url_safe or custom
#generator_type = "custom"
#generator_impl = "org.wso2.carbon.apimgt.keymgt.token.JWTGenerator"
header = "X-JWT-Assertion"
dialect = "http://wso2.org/claims"
algo = "SHA256withRSA"
user_claims = "default"
#user_claims = "custom"
#claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"

[apim.oauth_config]
outbound_auth_header_enabled = false
auth_header = "Authorization"
revoke_endpoint = "https://localhost:8243/revoke"
enable_token_encryption = false
enable_token_hashing = false

[apim.store]
url = "https://localhost:9443/store"
application_sharing_type = "default" #changed to type, saml, default, custom or rest # need to check the words # validate
#application_sharing_type = "custom"
#application_sharing_impl = "org.wso2.carbon.apimgt.impl.DefaultGroupIDExtractorImpl"
display_multiple_versions = false
display_deprecated_apis = false
comments_enabled = true
ratings_enabled = true
forum_enabled = true

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
allow_credentials = false

[apim.throttling]
service_url = "https://localhost:9443/services/"
username= "$conf{super_admin.username}"
password= "$conf{super_admin.password}"

enable_data_publishing = true
enable_policy_deployer = true
enable_block_condition = true

throttle_decision_endpoints = ["tcp://localhost:5672","tcp://localhost:5672"]

[[apim.throttling.nodes.group0]]
traffic_manager_url="tcp://localhost:9611"
traffic_manager_auth_url="ssl://localhost:9711"

[[apim.throttling.nodes.group0]]
traffic_manager_url="tcp://localhost:9611"
traffic_manager_auth_url="ssl://localhost:9711"

[[apim.throttling.nodes.group1]]
traffic_manager_url="tcp://localhost:9611"
traffic_manager_auth_url="ssl://localhost:9711"

[[apim.throttling.nodes.group1]]
traffic_manager_url="tcp://localhost:9611"
traffic_manager_auth_url="ssl://localhost:9711"

[apim.workflow]
enabled = false
service_url = "https://localhost:9445/bpmn"
username = "$conf{super_admin.username}"
password = "$conf{super_admin.password}"
callback_endpoint = "https://localhost:${mgt.transport.https.port}/api/am/publisher/v0.14/workflows/update-workflow-status"
token_endpoint = "https://localhost:${https.nio.port}/token"
client_registration_endpoint = "https://localhost:${mgt.transport.https.port}/client-registration/v0.14/register"
client_registration_username = "$conf{super_admin.username}"
client_registration_password = "$conf{super_admin.password}"
