name: MacOS + JDK 8

on:
  schedule:
  - cron: 0 0,8,16 * * *

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: cd ../../ & mvn clean install
