name: Ubuntu + JDK 11

on:
  schedule:
  - cron: 0 0,8,16 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: cd ../../ & mvn clean install
